name: oneshot-build
on: push
jobs:
  setup-containers:
    strategy:
      #fail-fast: true
      matrix:
          os: [  'el7']
 
    runs-on: ubuntu-latest
   
    container: 
      #image: ghcr.io/perfsonar/unibuild/${{ matrix.os }}:latest
      image: ghcr.io/perfsonar/docker-oneshot-builder/${{ matrix.os }}:latest
      volumes:
      - ${{ github.workspace }}:/app
        
    steps:
       - name: Check out Repo
         uses: actions/checkout@v3
       - name: pwd
         run: pwd
       - name: ls
         run: ls
 
        
