name: oneshot-build
on: push
jobs:
  setup-containers:
    strategy:
      #fail-fast: true
      matrix:
          os: [  'el7']
 
    runs-on: ubuntu-latest
   
    container: 
      #image: ghcr.io/perfsonar/unibuild/${{ matrix.os }}:latest
      image: ghcr.io/perfsonar/docker-oneshot-builder/${{ matrix.os }}:latest
      volumes:
      - ${{ github.workspace }}:/build
        
    steps:
       - name: Check out Repo
         uses: actions/checkout@v3
       - name: install dependancies repo
         run: yum -y install -y http://linux.mirrors.es.net/perfsonar/${{ matrix.os }}/x86_64/5/packages/perfsonar-repo-0.11-1.noarch.rpm
       - name: pwd
         run: pwd
       - name: ls
         run: ls
       - name: build
         run: make
 
        
